#!/usr/bin/env Rscript
# =============================================================================
# tools/gen_config.R — Generate everything that must agree with config/knobs.json
# =============================================================================
# The registry is the ONE declaration of a setting. Two artifacts are derived from it:
#
#   config/knobs.generated.sh         the shell mirror entrypoint.sh reads (the container has no
#                                     guaranteed JSON parser, and adding one to make a config file
#                                     readable would be a poor trade)
#   docs/routine_config.schema.json   the routine UI schema
#
# Both are generated rather than maintained, because a hand-kept schema is exactly what left
# GLOBIOM_subclass unrunnable for weeks: it had the code path and no enum entry, and nothing
# could notice. Run this after editing the registry; tests/test_config_registry.R fails if the
# checked-in artifacts do not match what this produces.
# =============================================================================

suppressPackageStartupMessages({
  if (!requireNamespace("jsonlite", quietly = TRUE)) {
    stop("Package 'jsonlite' is required to run tools/gen_config.R")
  }
  library(jsonlite)
})

find_root <- function() {
  if (file.exists("config/knobs.json")) {
    return(normalizePath(".", winslash = "/"))
  }
  cmd_args <- commandArgs(trailingOnly = FALSE)
  file_arg <- grep("^--file=", cmd_args, value = TRUE)
  if (length(file_arg) > 0) {
    p <- dirname(sub("^--file=", "", file_arg[1]))
    if (file.exists(file.path(p, "../config/knobs.json"))) {
      return(normalizePath(file.path(p, ".."), winslash = "/"))
    }
  }
  if (!is.null(sys.frames()) && length(sys.frames()) > 0) {
    for (frame in sys.frames()) {
      if (!is.null(frame$ofile)) {
        p <- dirname(frame$ofile)
        if (file.exists(file.path(p, "../config/knobs.json"))) {
          return(normalizePath(file.path(p, ".."), winslash = "/"))
        }
      }
    }
  }
  stop("Cannot determine repository root containing config/knobs.json")
}

ROOT <- find_root()
reg <- fromJSON(file.path(ROOT, "config/knobs.json"), simplifyVector = FALSE)
knobs <- reg$knobs

CORE_TASKS <- c("flat_fit", "flat_design", "nested", "report", "recover_bart", "bart_gate", "count", "test")
ALL_TASKS <- CORE_TASKS

sh_quote <- function(s) {
  if (is.null(s) || is.na(s)) s <- ""
  paste0("'", gsub("'", "'\\\\''", as.character(s)), "'")
}

# ---- shell mirror -------------------------------------------------------------------------
lines <- c(
  "# GENERATED by tools/gen_config.R from config/knobs.json -- do not edit.",
  "# Edit the registry and re-run the generator; the test suite checks these agree.",
  ""
)
reg_quotes <- vapply(knobs, function(k) sh_quote(k$name), character(1))
lines <- c(lines, sprintf("KNOB_REGISTRY=(%s)", paste(reg_quotes, collapse = " ")))
for (k in knobs) {
  n <- k$name
  lines <- c(lines, sprintf("KNOB_ENV_%s=%s", n, sh_quote(k$env)))
  lines <- c(lines, sprintf("KNOB_DEFAULT_%s=%s", n, sh_quote(k$default)))
  lines <- c(lines, sprintf("KNOB_SCOPE_%s=%s", n, sh_quote(k$scope)))
  blank_val <- if (!is.null(k$blank)) k$blank else ""
  lines <- c(lines, sprintf("KNOB_BLANK_%s=%s", n, sh_quote(blank_val)))
}
writeLines(lines, file.path(ROOT, "config/knobs.generated.sh"))

# ---- routine schema -----------------------------------------------------------------------
profile_files <- list.files(file.path(ROOT, "config/profiles"), pattern = "\\.env$")
profile_names <- sort(sub("\\.env$", "", profile_files))

props <- list(
  TASK = list(
    type = "string",
    title = "Workflow / Task",
    description = paste0(
      "Which workflow to run. A default set here is NOT enough: the platform ",
      "must pass the value into the container, as a command argument or in the ",
      "environment. The run log names the source it arrived from."
    ),
    default = "flat_fit",
    enum = CORE_TASKS
  ),
  PROFILE = list(
    type = "string",
    title = "Profile",
    description = paste0(
      "A named settings file in config/profiles/. Individual fields below ",
      "still override it. Recorded in the manifest, so a run is reproducible ",
      "from its profile name."
    ),
    default = "none",
    enum = c("none", profile_names)
  )
)

FAMILY_TASKS <- list(
  nested = "nested",
  flat = c("flat_design", "flat_fit"),
  count = "count",
  recover = "recover_bart",
  gate = "bart_gate"
)

tasks_for <- function(k) {
  out <- character(0)
  tasks <- k$tasks
  if (!is.null(tasks)) {
    for (fam in unlist(tasks)) {
      if (fam %in% names(FAMILY_TASKS)) {
        out <- c(out, FAMILY_TASKS[[fam]])
      }
    }
  }
  sort(unique(out))
}

for (k in knobs) {
  applies <- tasks_for(k)
  where <- if (length(applies) >= length(ALL_TASKS)) "" else sprintf("  [%s]", paste(sort(unlist(k$tasks)), collapse = ", "))
  label <- paste0(
    if (!is.null(k$label)) k$label else k$name,
    if (identical(k$scope, "model")) " [model spec]" else "",
    where
  )
  p <- list(
    type = "string",
    title = label,
    description = paste0(
      k$desc,
      if (identical(k$scope, "model")) "  CHANGES WHAT IS ESTIMATED -- runs differing here are not comparable with runs at the default." else ""
    ),
    default = as.character(k$default)
  )
  if (!is.null(k$enum)) {
    p$enum <- I(as.character(unlist(k$enum)))
  }
  props[[k$name]] <- p
}

props[["EXTRA"]] <- list(
  type = "string",
  title = "Overrides",
  description = paste0(
    "Overrides -- one-off settings as KEY=VALUE, comma separated, e.g. ",
    "'NITER=8000, USE_BART=TRUE'. Applied on top of the profile, and rejected if a ",
    "key is not a declared knob. 'none' for no overrides."
  ),
  default = "none"
)

for (n in names(props)) {
  lab <- props[[n]]$title
  if (is.null(lab)) lab <- n
  desc <- props[[n]]$description
  if (!startsWith(desc, lab)) {
    props[[n]]$description <- sprintf("%s -- %s", lab, desc)
  }
}

schema <- list(
  root = list(
    type = "object",
    title = "gamble-core routine configuration",
    description = "GENERATED from config/knobs.json by tools/gen_config.R. Field names are the environment variable names entrypoint.sh reads.",
    required = I("TASK"),
    properties = list()
  )
)

LEAN <- c(
  "TASK",
  "PROFILE",
  "CLASSIFICATION",
  "PIXEL_RES",
  "PIXEL_INTERSECT",
  "DESIGN_PATH",
  "VARIANT",
  "RE_BLOCK",
  "USE_BART",
  "SUBSAMPLE",
  "NITER",
  "N_CHAINS",
  "RUN_ID",
  "GAMBLE_WORK_DIR",
  "EXTRA"
)

lean_props <- list()
for (k in LEAN) {
  if (k %in% names(props)) {
    p_copy <- props[[k]]
    if (k == "GAMBLE_WORK_DIR") {
      p_copy$default <- "/mnt/wdrv/gamble-core"
    }
    lean_props[[k]] <- p_copy
  }
}
schema$root$properties <- lean_props

cat(toJSON(schema, auto_unbox = TRUE, pretty = 2), "\n", file = file.path(ROOT, "docs/routine_config.schema.json"), sep = "")

full <- schema
full$root$properties <- props
full$root$description <- paste0(schema$root$description, "  FULL variant: every knob. The lean one is usually what you want.")
cat(toJSON(full, auto_unbox = TRUE, pretty = 2), "\n", file = file.path(ROOT, "docs/routine_config.schema.full.json"), sep = "")

# Dedicated design assembly routine schema
DESIGN_FIELDS <- c(
  "TASK",
  "CLASSIFICATION",
  "PIXEL_RES",
  "PIXEL_INTERSECT",
  "Y_LAG",
  "DESIGN_PATH",
  "GAMBLE_WORK_DIR",
  "EXTRA"
)
design_props <- list()
for (k in DESIGN_FIELDS) {
  if (k %in% names(props)) {
    p_copy <- props[[k]]
    if (k == "TASK") {
      p_copy$default <- "flat_design"
      p_copy$enum <- I("flat_design")
    } else if (k == "GAMBLE_WORK_DIR") {
      p_copy$default <- "/mnt/wdrv/gamble-core"
    }
    design_props[[k]] <- p_copy
  }
}

design_schema <- list(
  root = list(
    type = "object",
    title = "gamble-core design matrix routine configuration",
    description = "GENERATED from config/knobs.json by tools/gen_config.R. Dedicated routine schema for assembling pixel model design dumps (TASK=flat_design).",
    required = I("TASK"),
    properties = design_props
  )
)
cat(toJSON(design_schema, auto_unbox = TRUE, pretty = 2), "\n", file = file.path(ROOT, "docs/routine_design.schema.json"), sep = "")

cat(sprintf("lean: %d fields | full: %d fields | design: %d fields\n", length(lean_props), length(props), length(design_props)))
cat("wrote config/knobs.generated.sh, docs/routine_config.schema.json, and docs/routine_design.schema.json\n")
