#!/usr/bin/env python3
"""Generate everything that must agree with config/knobs.json.

The registry is the ONE declaration of a setting. Two artifacts are derived from it:

  config/knobs.generated.sh    the shell mirror entrypoint.sh reads (the container has no
                               guaranteed JSON parser, and adding one to make a config file
                               readable would be a poor trade)
  docs/routine_config.schema.json   the routine UI schema

Both are generated rather than maintained, because a hand-kept schema is exactly what left
GLOBIOM_subclass unrunnable for weeks: it had the code path and no enum entry, and nothing
could notice. Run this after editing the registry; tests/test_config_registry.R fails if the
checked-in artifacts do not match what this produces.
"""
import json, subprocess, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
reg = json.loads((ROOT / "config/knobs.json").read_text())
knobs = reg["knobs"]


def project_tasks():
    out = []
    for d in sorted((ROOT / "projects").glob("*/gamble_model/run.sh")):
        name = d.parent.parent.name
        out += [f"{name}_{a}" for a in ("smoke", "design", "fit", "all", "more")]
    return out


CORE_TASKS = ["nested", "flat_design", "flat_fit", "count", "report", "test"]
ALL_TASKS = None  # set once project_tasks() is callable


def sh_quote(s):
    return "'" + str(s).replace("'", "'\\''") + "'"


# ---- shell mirror -------------------------------------------------------------------------
lines = ["# GENERATED by tools/gen_config.py from config/knobs.json -- do not edit.",
         "# Edit the registry and re-run the generator; the test suite checks these agree.",
         ""]
lines.append("KNOB_REGISTRY=(%s)" % " ".join(sh_quote(k["name"]) for k in knobs))
for k in knobs:
    n = k["name"]
    lines.append(f"KNOB_ENV_{n}={sh_quote(k['env'])}")
    lines.append(f"KNOB_DEFAULT_{n}={sh_quote(k['default'])}")
    lines.append(f"KNOB_SCOPE_{n}={sh_quote(k['scope'])}")
    lines.append(f"KNOB_BLANK_{n}={sh_quote(k.get('blank', ''))}")
(ROOT / "config/knobs.generated.sh").write_text("\n".join(lines) + "\n")

# ---- routine schema -----------------------------------------------------------------------
ALL_TASKS = project_tasks() + CORE_TASKS

props = {
    "TASK": {"type": "string", "title": "Workflow / Task",
             "description": "Which workflow to run. A default set here is NOT enough: the platform "
                            "must pass the value into the container, as a command argument or in the "
                            "environment. The run log names the source it arrived from.",
             "default": "BMLEH_Los1_CAPRI_smoke",
             "enum": project_tasks() + CORE_TASKS},
    "PROFILE": {"type": "string", "title": "Profile",
                "description": "A named settings file in config/profiles/. Individual fields below "
                               "still override it. Recorded in the manifest, so a run is reproducible "
                               "from its profile name.",
                "default": "none",
                "enum": ["none"] + sorted(p.stem for p in (ROOT / "config/profiles").glob("*.env"))},
}
FAMILY_TASKS = {"nested": ["nested"],
                "flat": ["flat_design", "flat_fit"],
                "project": project_tasks(),
                "count": ["count"]}


def tasks_for(k):
    out = []
    for fam in k.get("tasks", []):
        out += FAMILY_TASKS.get(fam, [])
    return sorted(set(out))


conditionals = []
for k in knobs:
    applies = tasks_for(k)
    # The applicability goes in the TITLE as well as an if/then block. A renderer that supports
    # draft-07 conditionals narrows the form; one that does not still shows which task a field
    # reaches, instead of offering factorized/iv on a project fit where it does nothing.
    where = "" if len(applies) >= len(ALL_TASKS) else "  [%s]" % ", ".join(sorted(set(
        f for f in k.get("tasks", []))))
    p = {"type": "string" if k["type"] != "integer" else "integer",
         "title": k["name"].replace("_", " ").title()
                  + (" [model spec]" if k["scope"] == "model" else "") + where,
         "description": k["desc"]
                        + ("  CHANGES WHAT IS ESTIMATED -- runs differing here are not comparable."
                           if k["scope"] == "model" else "")
                        + ("  Applies to: %s." % ", ".join(applies) if applies else "  Applies to no task."),
         "default": int(k["default"]) if (k["type"] == "integer" and k["default"]) else k["default"]}
    if "enum" in k:
        p["enum"] = k["enum"]
    props[k["name"]] = p
    # NO if/then BLOCK IS EMITTED. An earlier version added one per knob to narrow the form by task,
    # but a field declared in top-level `properties` cannot be hidden by a `then` branch -- then
    # only applies ADDITIONAL schema. Hiding would mean declaring the field ONLY inside the branch,
    # which in a renderer that ignores conditionals makes it vanish entirely: less clutter, and no
    # way to set it. Applicability therefore lives in the title and description, which every
    # renderer shows, and 25 inert blocks are not added to a file people have to read.
# The routine form marks EVERY declared property required and rejects a blank, so an optional
# field needs a sentinel it can hold. "auto" means the job works it out and logs what it did.
EXTRAS = [
    ("DESIGN_PATH", "auto", "Path to a pixel_model_inputs*.rds. 'auto' detects one on the drive or "
                            "/data and logs what it searched; set a path to remove all ambiguity."),
    ("PROJECT", "auto", "Chooses between staged design dumps for the generic tasks (nested, flat_*). "
                        "Project tasks carry their own project, so 'auto' is right for them."),
    ("GAMBLE_WORK_DIR", "/mnt/wdrv", "The FUSE mount results are collected from. output/ and results/ "
                                     "are symlinked here before the run."),
    ("GAMBLE_MASTER_PARQUET", "auto", "Covariate parquet, needed by a *_design task and irrelevant to "
                                      "a fit. 'auto' looks under /data."),
    ("GAMBLE_CASCADE_DATA", "auto", "cascadinggamble-core/data. 'auto' looks under /data."),
]
for extra, dflt, d in EXTRAS:
    props[extra] = {"type": "string", "title": extra.replace("_", " ").title(), "description": d,
                    "default": dflt}

# The form renders `title` above a text input but NOT above a dropdown, so an enum field arrives
# with no label at all -- "factorized" floating next to "intercept" with nothing naming either.
# Lead every description with the label so it is present whichever control the renderer picks.
for _n, _p in props.items():
    _lab = _p.get("title", _n)
    if not _p["description"].startswith(_lab):
        _p["description"] = "%s -- %s" % (_lab, _p["description"])

schema = {"$schema": "http://json-schema.org/draft-07/schema#",
          "title": "gamble-core routine configuration",
          "description": "GENERATED from config/knobs.json by tools/gen_config.py. Field names are the "
                         "environment variable names entrypoint.sh reads.",
          "type": "object", "required": ["TASK"], "properties": props}
(ROOT / "docs/routine_config.schema.json").write_text(json.dumps(schema, indent=2) + "\n")
print("wrote config/knobs.generated.sh (%d knobs) and docs/routine_config.schema.json (%d fields, %d tasks)"
      % (len(knobs), len(props), len(props["TASK"]["enum"])))
