#!/usr/bin/env python3
"""Generate everything that must agree with config/knobs.json.

The registry is the ONE declaration of a setting. Two artifacts are derived from it:

  config/knobs.generated.sh    the shell mirror entrypoint.sh reads (the container has no
                               guaranteed JSON parser, and adding one to make a config file
                               readable would be a poor trade)
  docs/routine_config.schema.json   the routine UI schema

Both are generated rather than maintained, because a hand-kept schema is exactly what left
GLOBIOM_subclass unrunnable for weeks: it had the code path and no enum entry, and nothing
could notice. Run this after editing the registry; tests/test_config_registry.R fails if the
checked-in artifacts do not match what this produces.
"""
import json, subprocess, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
reg = json.loads((ROOT / "config/knobs.json").read_text())
knobs = reg["knobs"]


def project_tasks():
    out = []
    for d in sorted((ROOT / "projects").glob("*/gamble_model/run.sh")):
        name = d.parent.parent.name
        out += [f"{name}_{a}" for a in ("smoke", "design", "fit", "all", "more")]
    return out


CORE_TASKS = ["nested", "flat_design", "flat_fit", "count", "report", "test"]


def sh_quote(s):
    return "'" + str(s).replace("'", "'\\''") + "'"


# ---- shell mirror -------------------------------------------------------------------------
lines = ["# GENERATED by tools/gen_config.py from config/knobs.json -- do not edit.",
         "# Edit the registry and re-run the generator; the test suite checks these agree.",
         ""]
lines.append("KNOB_REGISTRY=(%s)" % " ".join(sh_quote(k["name"]) for k in knobs))
for k in knobs:
    n = k["name"]
    lines.append(f"KNOB_ENV_{n}={sh_quote(k['env'])}")
    lines.append(f"KNOB_DEFAULT_{n}={sh_quote(k['default'])}")
    lines.append(f"KNOB_SCOPE_{n}={sh_quote(k['scope'])}")
(ROOT / "config/knobs.generated.sh").write_text("\n".join(lines) + "\n")

# ---- routine schema -----------------------------------------------------------------------
props = {
    "TASK": {"type": "string", "title": "Workflow / Task",
             "description": "Which workflow to run. A default set here is NOT enough: the platform "
                            "must pass the value into the container, as a command argument or in the "
                            "environment. The run log names the source it arrived from.",
             "default": "BMLEH_Los1_CAPRI_smoke",
             "enum": project_tasks() + CORE_TASKS},
    "PROFILE": {"type": "string", "title": "Profile",
                "description": "A named settings file in config/profiles/. Individual fields below "
                               "still override it. Recorded in the manifest, so a run is reproducible "
                               "from its profile name.",
                "default": "",
                "enum": [""] + sorted(p.stem for p in (ROOT / "config/profiles").glob("*.env"))},
}
for k in knobs:
    p = {"type": "string" if k["type"] != "integer" else "integer",
         "title": k["name"].replace("_", " ").title() + (" [model spec]" if k["scope"] == "model" else ""),
         "description": k["desc"] + ("  CHANGES WHAT IS ESTIMATED -- runs differing here are not comparable."
                                     if k["scope"] == "model" else ""),
         "default": int(k["default"]) if (k["type"] == "integer" and k["default"]) else k["default"]}
    if "enum" in k:
        p["enum"] = k["enum"]
    props[k["name"]] = p
for extra, d in (("DESIGN_PATH", "Absolute path to a pixel_model_inputs*.rds. Set to remove all ambiguity; "
                                 "empty auto-detects on the drive and logs what it searched."),
                 ("PROJECT", "Selects between staged design dumps for the generic tasks. Project tasks carry their own."),
                 ("GAMBLE_WORK_DIR", "FUSE mount results are collected from; output/ and results/ are symlinked here."),
                 ("GAMBLE_MASTER_PARQUET", "Covariate parquet for design builds. Auto-detected under /data when empty."),
                 ("GAMBLE_CASCADE_DATA", "cascadinggamble-core/data. Auto-detected under /data when empty.")):
    props[extra] = {"type": "string", "title": extra.replace("_", " ").title(), "description": d,
                    "default": "/mnt/wdrv" if extra == "GAMBLE_WORK_DIR" else ""}

schema = {"$schema": "http://json-schema.org/draft-07/schema#",
          "title": "gamble-core routine configuration",
          "description": "GENERATED from config/knobs.json by tools/gen_config.py. Field names are the "
                         "environment variable names entrypoint.sh reads.",
          "type": "object", "required": ["TASK"], "properties": props}
(ROOT / "docs/routine_config.schema.json").write_text(json.dumps(schema, indent=2) + "\n")
print("wrote config/knobs.generated.sh (%d knobs) and docs/routine_config.schema.json (%d fields, %d tasks)"
      % (len(knobs), len(props), len(props["TASK"]["enum"])))
